### ISSUE TITLE
Releases < 0.5.0 removed on pypi ?

### ISSUE THREAD

**Issue by thebaptiste** [ecmwf/ecmwflibs#12]
I was surprised that our CI suddenly stopped working a few days ago, because of the disappearance on pypi of ecmwflibs releases older than 0.5.0

Of course it's a good thing to encourage users to use new releases, but removing old releases is a rather rough way to do it...

**Comment by tlmquintino** [comment]
Apologies for the inconvenience. The problem is that we do not have enough space in the pypi repositories to store all the versions we would like. So periodically we need to delete older versions to make space for new ones.

**Comment by jjlk** [comment]
@tlmquintino 
Hi, same remarks than @thebaptiste.

I started to use this package as it provided a simple way to fix eccodes and cfgrib issues in anaconda environments. ecmwflibs is installed via pip in those environments.

Do you confirm that we shouldn't rely on the ecmwflibs Python package for long-term production purpose? By that I mean, for example, create a conda environment with a fixed version of ecmwflibs several time on a year time-scale?

Thanks.

**Comment by tlmquintino** [comment]
hi @jjlk 
We do not recommend ecmwflibs for operational environments for the reasons presented above.
ecmwflibs is designed for interactive environments, where installation of binaries is not allowed, such as google colab.
For operational environments we suggest:
* use conda (wither anaconda, miniconda or mamba). this is because we maintain the packages in those channels and we ensure they build against the binaries that also get installed through there.
* that you make a mirror of the conda channel where the packages are pulled, so that in the absence of network access to the public repo, or if the public repo is cleared of older versions, your operational system is not affected.
